pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code from GitHub...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Creating Python virtual environment...'
                sh 'cd docker-pipeline && python3 -m venv venv'

                echo 'Installing Python dependencies...'
                sh 'cd docker-pipeline && venv/bin/pip install -r requirements.txt'

                echo 'Checking Python version...'
                sh 'cd docker-pipeline && venv/bin/python --version'
            }
        }

        stage('Test') {
            steps {
                echo 'Running Python tests...'
                sh 'cd docker-pipeline && venv/bin/python test_app.py'
            }
        }

        stage('Docker Build') {
            steps {
                echo 'Building Docker image...'
                sh 'docker build -t jenkins-docker-practice:1.0 ./docker-pipeline'
            }
        }
    }

    post {
        success {
            echo 'BUILD SUCCESSFUL!'
        }

        failure {
            echo 'BUILD FAILED!'
        }

        always {
            echo 'Jenkins pipeline execution completed.'
        }
    }
}
